config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index' #home é o controller e index a ação (método). Aponta para o arquivo home_controller.rb
  resources :manufacturers
  resources :car_categories, only: %i[index new create show] 
  resources :car_models, only: %i[index new create show] # %i significa que é um array de simbolos. %w array de texto (strings). Tanto escrito dessa forma, como na linha abaixo estão corretos
  resources :rentals, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  validates :name, :daily_rate, :car_insurance, :third_part_insurance, presence: true # coloca os atributos e a regra da validação no final
  validates :name, uniqueness: true
  validates :daily_rate, :car_insurance, :third_part_insurance, numericality: { greater_than: 0 } #tem que ser maior que 0
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :manufacturer #significa que pertence a um fabricante
  belongs_to :car_category #significa que pertence a uma categoria
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :rentals

  def identification
    "#{name} - #{document}" # concatenando nome e cpf 
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :client
  belongs_to :car_category
  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  def index
    @car_categories = CarCategory.all
  end

  def show
    @car_category = CarCategory.find(params[:id])
  end
  
  def new
    @car_category = CarCategory.new
  end

  def create #Failure/Error: expect(page).to have_content('Categoria A') Capybara::ElementNotFound: Unable to find xpath "/html"
             #esse erro é pq o create não é um get, ou seja, não retorna uma view por padrão. Precisa ser criada.
    car_category_params = params.require(:car_category).permit(:name, :daily_rate, :car_insurance, :third_part_insurance) 
             # é uma variável que vai receber os valor dos params, ou seja, do que será preenchido pelo usuário através do arquivo new.html.erb
             # params.require(:car_category) --> :car_category é o nome da model dessa controller
             # no método .permit coloca os atributos que quer receber
    @car_category = CarCategory.new(car_category_params)
    @car_category.save

    redirect_to @car_category #aqui redireciona pro show. Pra isso essa rota precisa existir
  end
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  def index
    @car_models = CarModel.all
  end

  def show
    @car_model = CarModel.find(params[:id])
  end

  def new
    #@car_model = CarModel.new
  end

  def create
    car_model_params = params.require(:car_model).permit(:name, :fuel_type, :motorization, :year, :manufacturer_id, :car_category_id)
    @car_model = CarModel.new(car_model_params)
    @car_model.save
    redirect_to @car_model
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end 

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy] #esse método só vale para os métodos show, edit e update
    def index
        @manufacturers = Manufacturer.all #manufacturers (vai usar na view) é a variável que vai guardar todas os registros dessa tabela
                                          #sempre que tiver @ é pra essa variável ser usada na view
    end

    def show
    end

    def new
        @manufacturer = Manufacturer.new
    end

    def create
      @manufacturer = Manufacturer.new(manufacturer_params)

      if @manufacturer.save
        redirect_to @manufacturer
      else
        render 'new' #redireciona para view do manufacturer
      end
    end

    def edit
    end

    def update
      if @manufacturer.update(manufacturer_params)
        redirect_to @manufacturer
      else
        render 'edit'
      end
    end

    def destroy
      @manufacturer.delete
      redirect_to manufacturers_path
    end

    private

    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end 

    def manufacturer_params
      # { name: params[:manufacturer][:name] }
      params.require(:manufacturer).permit(:name)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = Rental.all
  end

  def new
    @rental = Rental.new
    @car_categories = CarCategory.all # será usado em new de rental
    @clients = Client.all # será usado em new de rental
  end

  def create
    @rental = Rental.new(params.require(:rental).permit(:start_date, :end_date, :car_category_id, :client_id))
    if @rental.save
      redirect_to rentals_path
    else
      @car_categories = CarCategory.all 
      @clients = Client.all 
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/car_categories/index.html.erb
<h1>Categorias de Carros</h1>
<% if @car_categories.any? %>
<table>
  <thead> 
    <tr> 
      <th>Categoria</th> 
      <th>Diária</th>
    </tr>
  </thead>
  <tbody> 
  <% @car_categories.each do |category| %>
    <tr>
      <td><%= link_to "Categoria #{category.name}", category %></td>
      <td><%= number_to_currency category.daily_rate %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
  <p>Nenhuma categoria cadastrada</p>
<% end %>
<%= link_to 'Registrar nova categoria de carro', new_car_category_path %>
<%= link_to 'Voltar', root_path %>

app/views/car_categories/new.html.erb
<h1>Nova categoria de carro</h1>

<%= form_with(model: @car_category) do |f| %>
  <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
  </div>
  <div>
      <%= f.label :daily_rate %>
      <%= f.text_field :daily_rate %>
  </div>
  <div>
      <%= f.label :car_insurance %>
      <%= f.text_field :car_insurance %>
  </div>
  <div>
      <%= f.label :third_part_insurance %>
      <%= f.text_field :third_part_insurance %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/car_categories/show.html.erb
<h1>Categoria <%= @car_category.name %></h1> <!-- ao criar essa linha de comando, precisa trazer dados no método show da controller pois sem ele, o sistema dá erro por não encontrar os dados -->
<dl>
  <dt>Diária:</dt>
  <dd><%= number_to_currency @car_category.daily_rate %></dd>

  <dt>Seguro:</dt>
  <dd><%= number_to_currency @car_category.car_insurance %></dd>  

  <dt>Seguro para terceiros:</dt>
  <dd><%= number_to_currency @car_category.third_part_insurance %></dd>
</dl>

app/views/car_models/index.html.erb
<h1>Modelos de Carros</h1>

<table>
  <thead> <!-- cabeçalho -->
    <tr> <!-- row -- a tabela tem multiplas linhas -->
      <th>Fabricante</th> <!-- o h de th é do head -->
      <th>Nome</th>
      <th>Categoria</th>
    </tr>
  </thead>
  <tbody> <!-- corpo -->
  <% @car_models.each do |car_model| %>
    <tr> 
      <td><%= car_model.manufacturer.name %></td> <!-- No body é td -->
      <td><%= car_model.name %></td>
      <td><%= car_model.car_category.name%></td> <!-- como precisa trazer o nome da categoria, precisa acessar essa "tabela" pra acessar o nome -->
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Cadastrar novo modelo de carro', new_car_model_path %>

app/views/car_models/new.html.erb
<h1>Cadastrar modelo de carro</h1>

<%= form_with(model: CarModel.new, local: true) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :fuel_type, 'Combustível' %>
    <%= f.text_field :fuel_type %>
  </div>
  <div>
    <%= f.label :motorization, 'Motor' %>
    <%= f.text_field :motorization %>
  </div>
  <div>
    <%= f.label :year, 'Ano' %>
    <%= f.text_field :year %>
  </div>
  <div>
    <%= f.label :manufacturer_id, 'Fabricante' %> <!-- aqui vai manufacturer_id pq é o valor armazenado em car_model-->
    <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name) %> <!-- o primeiro é a coluna manufacturer_id que é a coluna que está em CarModel pois lá não é armazenado o nome e sim o id-->
                                                                               <!-- o segundo é Manufacturer.all que são todos os fabricantes cadastrados no banco. -->
                                                                               <!-- O terceiro, é o id dele no controller do manufacturer-->
                                                                               <!-- o quarto elemento, é o que vai exibir na tela pro usuário-->
  <div>
    <%= f.label :car_category_id, 'Categoria' %> 
    <%= f.collection_select(:car_category_id, CarCategory.all, :id, :name) %> 
  </div>
  <%= f.submit 'Enviar' %> 
<% end %>

app/views/car_models/show.html.erb
<h1><%= @car_model.name %></h1>
<dl>
  <dt>Fabricante:</dt>
  <dd><%= @car_model.manufacturer.name %></dd> <!-- tá vindo do model no belongs_to-->
  <dt>Categoria:</dt>
  <dd><%= @car_model.car_category.name %></dd>
  <dt>Combustível:</dt>
  <dd><%= @car_model.fuel_type %></dd>
  <dt>Motor:</dt>
  <dd><%= @car_model.motorization %></dd>
  <dt>Ano:</dt>
  <dd><%= @car_model.year %></dd>
</dl>

app/views/home/index.html.erb
<%= flash[:notice] %> <!-- mensagem interna - nesse caso foi de sucesso ao logar sistema -->

<h1>Rental Cars</h1>

<h2>Bem vindo ao sistema de gestão de locação</h2>


<%= link_to 'Entrar', new_user_session_path %>
<%= link_to 'Fabricantes', manufacturers_path %> <!--tag usada para ruby com html. A palavra Fabricantes é o que vai aparecer na página. O manufactures_path é o link da rota -->
<%= link_to 'Categorias de Carros', car_categories_path %>
<%= link_to 'Modelos de Carros', car_models_path %>
<%= link_to 'Locações', rentals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalCars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/_form.html.erb
<% if @manufacturer.errors.full_messages.any? %>
  <p>Não foi possível salvar, verifique os erros abaixo:</p>
  <ul>
  <% @manufacturer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with(model: @manufacturer) do |f| %>
   <%= f.label(:name, 'Nome') %>
   <%= f.text_field(:name) %>

   <%= f.submit('Enviar') %>

<% end %>

app/views/manufacturers/edit.html.erb
<h1>Editar Fabricante</h1>

<%= render 'form' %>

app/views/manufacturers/index.html.erb
<h1>Fabricantes</h1>

<% @manufacturers.each do |m| %> <!-- @manufacturers vem da controller -->
    <h3><%= link_to m.name, manufacturer_path(m.id) %></h3> <!-- manufacturer no singular pq no routes, o prefixo é esse + "_path" pra visualizar um unico registro na tela -->
<% end %>

<% if @manufacturers.empty? %>
  <p>Nenhum fabricante cadastrado</p>
<% end %>

<%= link_to 'Registrar novo fabricante', new_manufacturer_path %>

<%= link_to 'Voltar', root_path %>

app/views/manufacturers/new.html.erb
<h1>Novo Fabricante</h1>

<%= render 'form' %>

app/views/manufacturers/show.html.erb
<%= @manufacturer.name %>
<%= link_to 'Editar', edit_manufacturer_path(@manufacturer.id) %>
<%= link_to('Apagar', manufacturer_path(@manufacturer.id), method: :delete) %>

<%= link_to 'Voltar', manufacturers_path %>

app/views/rentals/index.html.erb
<h1>Locações</h1>

<% @rentals.each do |rental| %>
  <div>
    <p>
      <strong>Data inicial: </strong><%= l rental.start_date %>   <!-- precisa do "l" do i18n.localize por conta do formato do dado. Na view e no controller pode usar só "l", no model tem q colocar i18n.l -->
    </p>
    <p>
      <strong>Data final: </strong><%= l rental.end_date %>   <!-- precisa do "l" do i18n por conta do formato do dado-->
    </p>
    <p>
      <strong>Client: </strong><%= rental.client.identification %>
    </p>
    <p>
      <strong>Categoria: </strong><%= rental.car_category.name %>  
    </p>
  </div>
<% end %>

<%= link_to 'Registrar locação', new_rental_path %>

app/views/rentals/new.html.erb
<h1>Nova locação</h1>

<% @rental.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @rental, local: true do |f| %>
  <div>
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>
  <div>
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>
  <div>
    <%= f.label :car_category_id %> 
    <%= f.collection_select(:car_category_id, @car_categories, :id, :name) %> 
  <div>
    <%= f.label :client_id %> 
    <%= f.collection_select(:client_id, @clients, :id, :name) %> 
  </div>
  <%= f.submit 'Enviar' %> 
<% end %>